# .github/workflows/ci.yml
name: Continuous Integration

on:
  pull_request:
    branches:
      [main]

jobs:
  lint-ant-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ruff
        uses: uv run ruff check